<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <AssemblyName>YukiMod.Tests</AssemblyName>
    <RootNamespace>YukiMod.Tests</RootNamespace>
    <RestoreSources>../../../TestTheSpire/artifacts/packages;https://api.nuget.org/v3/index.json</RestoreSources>
    <Sts2Path Condition="'$(Sts2Path)' == ''">D:/Steam/steamapps/common/Slay the Spire 2</Sts2Path>
    <Sts2MainModId>YukiMod</Sts2MainModId>
    <Sts2TestModId>YukiMod.Tests</Sts2TestModId>
    <Sts2TestModName>YukiMod.Tests</Sts2TestModName>
    <Sts2TestModAuthor>lozalia</Sts2TestModAuthor>
    <Sts2TestDisabledModIds>Fei;KalipeiMod;KaylaMod;MeiLinMod;StS2_MeiLinTexturePack;STS2-RitsuLib</Sts2TestDisabledModIds>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../YukiMod.csproj" />
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="TestTheSpire" Version="0.1.0" />
  </ItemGroup>
</Project>
